version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddemdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}  # Utilisation de la variable dynamique du pipeline Jenkins
    depends_on:
      - db
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kaddemdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: null
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
