global:
  scrape_intervel : 15s
  evaluation_interval : 15s

scrape_configs:
  - job_name: 'kaddem-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['localhost:8080']
