global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['kaddem-backend:8089']
  - job_name: 'mysql'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mysqld-exporter:9104']
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['kaddem-prometheus:9090']  # Ajout de la cible pour kaddem-prometheus
